FROM alpine:3.6 as alpine

RUN apk add -U --no-cache ca-certificates

FROM scratch
WORKDIR /bin
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 9000

ADD release/boxci-agent /bin/
COPY release/boxci-agent.env /bin/.env

ENTRYPOINT ["./boxci-agent"]